<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_employee</name>
   <tag></tag>
   <elementGuidId>48a8f393-7efa-4e78-9e41-7138bcbd966a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiButtonBase-root.MuiListItemButton-root.MuiListItemButton-gutters.MuiListItemButton-root.MuiListItemButton-gutters.css-1pcmm56</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/nav/div/div/div[2]/div/div/div[2]/div/div/div/div/ul/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b7311779-197f-4ed7-be84-96f5e303a881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiListItemButton-root MuiListItemButton-gutters MuiListItemButton-root MuiListItemButton-gutters css-1pcmm56</value>
      <webElementGuid>a2e02de0-7f54-4726-9b73-1c8e03c18e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d5ef56b9-c8a2-4b09-bd5e-bb81c252afa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>671c1de5-50e9-4364-a658-1f23c750e456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>depth</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>db00ecc0-6f42-4171-b2fd-7d91422d23ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>employee</value>
      <webElementGuid>ca319f02-2826-42cb-a6e0-9e69fb0ab7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;MuiBox-root css-fwi0lb&quot;]/nav[@class=&quot;MuiBox-root css-1y6sui9&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-docked css-oms1ax&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiDrawer-paper MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft css-1qo71ce&quot;]/div[@class=&quot;css-jjtu05&quot;]/div[@class=&quot;css-bbmev7&quot;]/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/div[@class=&quot;css-j7qwjs&quot;]/ul[@class=&quot;MuiList-root css-13cr43y&quot;]/div[@class=&quot;MuiButtonBase-root MuiListItemButton-root MuiListItemButton-gutters MuiListItemButton-root MuiListItemButton-gutters css-1pcmm56&quot;]</value>
      <webElementGuid>fabd22c3-c4fd-4169-95f7-35f246473b8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/nav/div/div/div[2]/div/div/div[2]/div/div/div/div/ul/div</value>
      <webElementGuid>8d52dba7-56d3-4ce1-af63-c5ea0c75775a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/div</value>
      <webElementGuid>7cb46f9a-142c-44eb-b2f2-8a7547706d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'employee' or . = 'employee')]</value>
      <webElementGuid>b1c37284-ab98-4219-b62b-40379878ac09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
