<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_employee</name>
   <tag></tag>
   <elementGuidId>a1f55f91-e021-474c-b5b4-76e6d5bea6f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.MuiTypography-root.MuiTypography-body2.MuiTypography-noWrap.MuiListItemText-primary.css-b1u5mt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/nav/div/div/div[2]/div/div/div[2]/div/div/div/div/ul/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cf04b03c-1f54-4afc-ba6a-8074e9f3e8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-body2 MuiTypography-noWrap MuiListItemText-primary css-b1u5mt</value>
      <webElementGuid>c411f90e-85c9-4a91-be3b-58f41c9ee9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>employee</value>
      <webElementGuid>a799ed57-ddc3-45da-8bdd-d656a62e8c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;MuiBox-root css-fwi0lb&quot;]/nav[@class=&quot;MuiBox-root css-1y6sui9&quot;]/div[@class=&quot;MuiDrawer-root MuiDrawer-docked css-oms1ax&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation0 MuiDrawer-paper MuiDrawer-paperAnchorLeft MuiDrawer-paperAnchorDockedLeft css-1qo71ce&quot;]/div[@class=&quot;css-jjtu05&quot;]/div[@class=&quot;css-bbmev7&quot;]/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/div[@class=&quot;css-j7qwjs&quot;]/ul[@class=&quot;MuiList-root css-13cr43y&quot;]/div[@class=&quot;MuiButtonBase-root MuiListItemButton-root MuiListItemButton-gutters MuiListItemButton-root MuiListItemButton-gutters css-1pcmm56&quot;]/div[@class=&quot;MuiListItemText-root css-xdiy5h&quot;]/span[@class=&quot;MuiTypography-root MuiTypography-body2 MuiTypography-noWrap MuiListItemText-primary css-b1u5mt&quot;]</value>
      <webElementGuid>a7737ad5-5812-4899-aca2-ee0516120853</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/nav/div/div/div[2]/div/div/div[2]/div/div/div/div/ul/div/div[2]/span</value>
      <webElementGuid>654a7834-046b-40e2-87e3-9117fd8466cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/span</value>
      <webElementGuid>5cd6175e-46e4-4e79-b130-9a29bde0d636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'employee' or . = 'employee')]</value>
      <webElementGuid>85539d37-b8f2-426a-89fe-5789f665450d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
