<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_UsernameUsernamePasswordPassword</name>
   <tag></tag>
   <elementGuidId>a0c69e2c-c8e8-4283-9aec-026617cd2b26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-ovnx7g</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div/div/form/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7f9ccf6-3777-4fb2-aebf-5f546de41349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-ovnx7g</value>
      <webElementGuid>f55a1d9e-e756-4a31-932d-dab344b2410e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UsernameUsernamePasswordPassword</value>
      <webElementGuid>142452e4-feb7-4502-9865-42afb17d6166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/main[@class=&quot;css-82n2xo&quot;]/div[@class=&quot;css-19bhn4g&quot;]/div[@class=&quot;MuiBox-root css-1yw1gui&quot;]/div[@class=&quot;css-pqqgcv&quot;]/form[1]/div[@class=&quot;css-ovnx7g&quot;]</value>
      <webElementGuid>60a4ddac-8b2b-4b4e-a468-30b408deeb13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div/form/div</value>
      <webElementGuid>19c949e2-de53-4412-b248-2325cb4b5ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>3f5a6c31-c9fd-4f4f-890f-6a151001765b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'UsernameUsernamePasswordPassword' or . = 'UsernameUsernamePasswordPassword')]</value>
      <webElementGuid>3fd6bbde-ea56-421d-b073-65b459bf3480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
