<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_UsernameUsernamePasswordPassword</name>
   <tag></tag>
   <elementGuidId>093e2f4b-2575-4198-a33d-7dbc6995524f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.css-ovnx7g</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/main/div/div/div/form/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6f73ab4c-c620-49c3-b415-1a7543c8fa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-ovnx7g</value>
      <webElementGuid>eaea5060-c2aa-490f-8ed3-c7d091f0efbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UsernameUsernamePasswordPassword</value>
      <webElementGuid>8101c407-676b-44f2-bd95-6c8f544fa4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/main[@class=&quot;css-82n2xo&quot;]/div[@class=&quot;css-19bhn4g&quot;]/div[@class=&quot;MuiBox-root css-1yw1gui&quot;]/div[@class=&quot;css-pqqgcv&quot;]/form[1]/div[@class=&quot;css-ovnx7g&quot;]</value>
      <webElementGuid>2849dc0a-bdb7-47d9-9705-66c627895572</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/main/div/div/div/form/div</value>
      <webElementGuid>2c51f005-8cda-48a2-9145-9431069104ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div</value>
      <webElementGuid>1c58a2d5-0e3f-4305-897a-d9a2807cc277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'UsernameUsernamePasswordPassword' or . = 'UsernameUsernamePasswordPassword')]</value>
      <webElementGuid>2fdf01f7-82fa-4480-b284-f2ea51153f03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
