<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_1997</name>
   <tag></tag>
   <elementGuidId>6f0a3950-46e2-478f-889c-7dbc0e55c280</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[106]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d58b01c3-e9a6-4a5d-9f02-08478e4b8e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8948cce5-c2da-4863-95e3-be729b411201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f32cfc46-ab51-49ca-9807-1fbb56ee9457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivatePickersYear-yearButton css-y40400</value>
      <webElementGuid>c8862ccf-99e5-47c9-a4a5-80204eb4dd1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1997</value>
      <webElementGuid>62207c86-5978-443c-bf11-7dfb47b8dbd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[@class=&quot;pr-0&quot;]/div[@class=&quot;MuiPickersPopper-root css-1mtsuo7 MuiPopperUnstyled-root&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation8 MuiPickersPopper-paper css-1qf6zfl&quot;]/div[@class=&quot;MuiCalendarOrClockPicker-root css-j7qwjs&quot;]/div[@class=&quot;css-epd502&quot;]/div[@class=&quot;MuiCalendarPicker-root css-1brzq0m&quot;]/div[@class=&quot;MuiPickersFadeTransitionGroup-root MuiCalendarPicker-viewTransitionContainer css-1h73gvd&quot;]/div[1]/div[@class=&quot;MuiYearPicker-root css-f09ynp&quot;]/div[@class=&quot;PrivatePickersYear-root PrivatePickersYear-modeDesktop css-j9zntq&quot;]/button[@class=&quot;PrivatePickersYear-yearButton css-y40400&quot;]</value>
      <webElementGuid>589a06a5-e8e8-4a7d-a88f-86580b6fc3b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[106]</value>
      <webElementGuid>f60eca88-091a-4565-a7bd-09bc51930f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[98]/button</value>
      <webElementGuid>4f69d1ab-90fd-4062-8335-5f9348d8d04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '1997' or . = '1997')]</value>
      <webElementGuid>c40101a4-a014-4930-80e3-35c7b42cc717</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
