<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Email Address is required</name>
   <tag></tag>
   <elementGuidId>43d0b424-b07b-4082-af88-246fcda5eb9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':rn:-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>319e96e4-25d1-4af9-9266-8b29002cdcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained Mui-required css-1vgir83</value>
      <webElementGuid>6edae6aa-ee31-4aae-9b47-5b00d0dff3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rn:-helper-text</value>
      <webElementGuid>ed87a7b5-f043-4d71-b34e-c2ca57de989e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email Address is required</value>
      <webElementGuid>615a1dc2-2bf8-4c3a-9350-930157a94883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rn:-helper-text&quot;)</value>
      <webElementGuid>373c58fa-1270-44a1-a935-4dfe18499b96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':rn:-helper-text']</value>
      <webElementGuid>6bffcfa8-ff0c-4ab3-9c0f-dd269e2efd1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/form/div/div/div/div[8]/div[3]/p</value>
      <webElementGuid>91fe72a8-d6d0-4a8a-9c7e-e612b8373e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[3]/p</value>
      <webElementGuid>b911387f-4010-4343-be05-b9043620d427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':rn:-helper-text' and (text() = 'Email Address is required' or . = 'Email Address is required')]</value>
      <webElementGuid>46e85e92-59c9-4757-aaa1-24187dd204ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
