<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Gender is required</name>
   <tag></tag>
   <elementGuidId>c044990f-6077-4f41-984f-4f291b8fe11a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':ra:-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b7be8df2-ff4e-4a4c-8bc7-db6890bb3d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained MuiFormHelperText-filled Mui-required css-1vgir83</value>
      <webElementGuid>10894f5b-eb93-4d4f-a049-14dc8885cd52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:ra:-helper-text</value>
      <webElementGuid>06c91245-0c2a-4ffe-a41d-42a376679f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Gender is required</value>
      <webElementGuid>612b23f6-bb2b-4c38-9108-f330cbf1437a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:ra:-helper-text&quot;)</value>
      <webElementGuid>e51458bf-a6e1-4831-b050-b42238362614</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':ra:-helper-text']</value>
      <webElementGuid>afa140cb-560c-48f0-a808-a45598fd2201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/form/div/div/div/div[2]/div[4]/p</value>
      <webElementGuid>6ac615f1-ca61-4298-8fcc-36c9da6a4cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/p</value>
      <webElementGuid>42670d1e-eeb9-4f96-aba9-04bc4c6a8fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':ra:-helper-text' and (text() = 'Gender is required' or . = 'Gender is required')]</value>
      <webElementGuid>c32d83bc-85c2-4146-afc1-5c7b9a9d2c4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
