<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Postal code is required</name>
   <tag></tag>
   <elementGuidId>b50ec940-84eb-4bfc-b84f-f5f8a60bf758</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':rk:-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>6135c1a4-75a8-4838-96b1-14d62eea3f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained Mui-required css-1vgir83</value>
      <webElementGuid>1e4e9cd4-93a8-4b2e-a306-91fe3b5c26e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rk:-helper-text</value>
      <webElementGuid>10479b28-8e1e-4190-8d66-b6a94d89cd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Postal code is required</value>
      <webElementGuid>0a1b98bf-0171-4b89-8f87-1fa925ddd96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rk:-helper-text&quot;)</value>
      <webElementGuid>0fd1846e-d40a-4f6d-82dd-81e5ec7b6392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':rk:-helper-text']</value>
      <webElementGuid>daecdd95-b6f6-4cfa-aeaa-f76a0a74bf19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/form/div/div/div/div[6]/div[3]/p</value>
      <webElementGuid>d30a7afe-0512-443e-96a1-9d989e0be2c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[3]/p</value>
      <webElementGuid>e0dd43fd-85fe-4041-ba65-eed8c7b9ad31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':rk:-helper-text' and (text() = 'Postal code is required' or . = 'Postal code is required')]</value>
      <webElementGuid>6d8ceb63-413a-4672-992c-179a693f9510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
