<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Status is required</name>
   <tag></tag>
   <elementGuidId>4b72056b-cd21-4db8-b5e0-d0f0e8aad460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':rd:-helper-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>41fb24b2-e9b4-4a2e-8294-d5c81d638b9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiFormHelperText-root Mui-error MuiFormHelperText-sizeMedium MuiFormHelperText-contained MuiFormHelperText-filled Mui-required css-1vgir83</value>
      <webElementGuid>ea03fcbb-b743-4dc7-bf39-63f1e42eb67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rd:-helper-text</value>
      <webElementGuid>cfa806e5-eb7c-42c8-ba51-169b034740d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Status is required</value>
      <webElementGuid>06f0e706-f4e8-4e0f-b31c-69c209ce40b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rd:-helper-text&quot;)</value>
      <webElementGuid>eda11c38-0386-4593-bef5-86acf8806e60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':rd:-helper-text']</value>
      <webElementGuid>401bfd7b-bb5a-4eef-9d69-ee48b28d4f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/form/div/div/div/div[2]/div[7]/p</value>
      <webElementGuid>21ee84e7-3d0b-4ed2-a608-bf32a7509b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/p</value>
      <webElementGuid>f076beac-4cf3-4549-9995-d643c1ae9851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':rd:-helper-text' and (text() = 'Status is required' or . = 'Status is required')]</value>
      <webElementGuid>ce15a263-07a8-4580-9a82-3d48d2e009f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
