<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose hereDraftPendingApprovedRejected</name>
   <tag></tag>
   <elementGuidId>1d4876c4-5e1b-423c-9a95-fc08da671de6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=':rd:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1c4f31ea-500f-436b-805d-399b03734429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiNativeSelect-select MuiNativeSelect-outlined MuiInputBase-input MuiOutlinedInput-input css-1p2ub1r</value>
      <webElementGuid>805ca268-4490-4ee2-b9d3-db4b9a7e7f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b26c62e-684c-45ec-ad56-873629879410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:rd:</value>
      <webElementGuid>2cbf6b8d-6bf8-41f0-8f6b-32816c4a0adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>1b5096b8-9617-4bb0-a90b-0b3238c0f81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose hereDraftPendingApprovedRejected</value>
      <webElementGuid>d8cfe0a8-037f-4936-a4fa-7019bd12fde8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:rd:&quot;)</value>
      <webElementGuid>82fc2f6c-14a7-44d1-9a8d-c8303ca54cbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id=':rd:']</value>
      <webElementGuid>277e3dd1-41c0-4331-9a0c-0ad7ea6cfa94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/form/div/div/div/div[2]/div[7]/div/select</value>
      <webElementGuid>be7f2e96-9bee-4177-92fd-e03cc63ed0d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/select</value>
      <webElementGuid>691a9378-abbf-4499-abb9-49af0ac661fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = ':rd:' and @name = 'status' and (text() = 'Choose hereDraftPendingApprovedRejected' or . = 'Choose hereDraftPendingApprovedRejected')]</value>
      <webElementGuid>b224d6d0-cc24-4db5-8511-b820a38cfd2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
