<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose hereCare GiverSupervisorAdmin_2ab203</name>
   <tag></tag>
   <elementGuidId>8370888c-6554-4473-b372-ff3acbb6422d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id=':re:']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e46ef0ad-b792-48cd-82bb-779ced8513d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiNativeSelect-select MuiNativeSelect-outlined MuiInputBase-input MuiOutlinedInput-input css-1p2ub1r</value>
      <webElementGuid>441a8031-ca84-4d89-9b18-e19eb2a4a472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>693360bc-f663-491d-96ab-24cada98d324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:re:</value>
      <webElementGuid>f8896b31-74fa-4cad-a6ee-66796e31052d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>role</value>
      <webElementGuid>ca3979c5-9a69-4f82-9bb3-46213cfe9866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose hereCare GiverSupervisorAdminDriverOffice Staff</value>
      <webElementGuid>e3bbe6a5-08b0-49bb-b7e5-2a2af6197797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:re:&quot;)</value>
      <webElementGuid>37da53c9-0f8a-4977-b603-febba9ac03a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id=':re:']</value>
      <webElementGuid>bc892b86-eb66-48af-92b1-a2d5f094f33e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/main/div/form/div/div/div/div[2]/div[8]/div/select</value>
      <webElementGuid>d3f0a5ac-dcef-467e-9e57-85feeda1c1c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>70efa5ff-5655-4733-8ac1-a8c947047edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = ':re:' and @name = 'role' and (text() = 'Choose hereCare GiverSupervisorAdminDriverOffice Staff' or . = 'Choose hereCare GiverSupervisorAdminDriverOffice Staff')]</value>
      <webElementGuid>101a3922-2add-4373-8f32-c9052cc5108e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
